version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ralph-trends-db
    environment:
      POSTGRES_DB: trend_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ralph_trends_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - trends-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d trend_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ralph-trends-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trends-network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ralph_cache_2024

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ralph-trends-app
    environment:
      NODE_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: trend_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ralph_trends_2024
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ralph_cache_2024
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./logs:/app/logs
    networks:
      - trends-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  trends-network:
    driver: bridge